{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-stable-diffusion.fullname" . }}
  labels:
    {{- include "app-stable-diffusion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-stable-diffusion.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app-stable-diffusion.labels" . | nindent 8 }}
        {{- include "app-stable-diffusion.apoloPodLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.deployment.healthChecks.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.deployment.healthChecks.delay }}
            httpGet:
              path: {{ .Values.deployment.healthChecks.endpoint }}
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.deployment.healthChecks.delay }}
            httpGet:
              path: {{ .Values.deployment.healthChecks.endpoint }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          {{- if .Values.deployment.env }}
          env:
          {{- range $k, $v := .Values.deployment.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          {{- end }}
          {{- with .Values.deployment.args -}}
          args:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
{{- end }}
