{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- include "app.apoloPodLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{/*      {{- if .Values.modelDownload.initEnabled }}*/}}
{{/*      initContainers:*/}}
{{/*        - name: download-model*/}}
{{/*          image: "{{ .Values.modelDownload.image.repository }}:{{ .Values.modelDownload.image.tag }}"*/}}
{{/*          volumeMounts:*/}}
{{/*            {{- if .Values.HFCacheVolume.enabled }}*/}}
{{/*            - name: huggingface-cache*/}}
{{/*              mountPath: {{ .Values.api.env.HUGGINGFACE_HUB_CACHE }}*/}}
{{/*            {{- end }}*/}}
{{/*          env:*/}}
{{/*          {{- range $k, $v := .Values.api.env }}*/}}
{{/*            - name: {{ $k }}*/}}
{{/*              {{- if kindIs "string" $v }}*/}}
{{/*              value: {{ $v | quote }}*/}}
{{/*              {{- else }}*/}}
{{/*              {{ $v | toYaml | nindent 14 }}*/}}
{{/*              {{- end }}*/}}
{{/*          {{- end }}*/}}
{{/*          command: [ "/bin/sh", "-c" ]*/}}
{{/*          args:*/}}
{{/*            - "pip install -U 'huggingface_hub[cli]'==0.29.1 && huggingface-cli download {{ .Values.model.modelHFName }} --local-dir /mnt/models/Diffusers/ --repo-type model"*/}}
{{/*      {{- end }}*/}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /sdapi/v1/options
              port: http
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /sdapi/v1/options
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
{{/*            {{- if .Values.HFCacheVolume.enabled }}*/}}
{{/*            - name: huggingface-cache*/}}
{{/*              mountPath: {{ .Values.api.env.HUGGINGFACE_HUB_CACHE }}*/}}
{{/*            {{- end }}*/}}
          {{- if .Values.api.env }}
          env:
          {{- range $k, $v := .Values.api.env }}
            - name: {{ $k }}
              {{- if kindIs "string" $v }}
              value: |
                {{ $v | quote }}
              {{- else }}
              {{ $v | toYaml | nindent 14 }}
              {{- end }}

          {{- end }}
          {{- end }}
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      {{- if .Values.HFCacheVolume.enabled }}
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: {{ include "app.fullname" . }}-cache
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
{{- end }}
