{{- if .Values.stablestudio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stablestudio.fullname" . }}
  labels:
    {{- include "stablestudio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.stablestudio.replicaCount }}
  selector:
    matchLabels:
      {{- include "stablestudio.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.stablestudio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stablestudio.labels" . | nindent 8 }}
        {{- include "stablestudio.apoloPodLabels" . | nindent 8 }}
    spec:
      {{- with .Values.stablestudio.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.stablestudio.image.repository }}:{{ .Values.stablestudio.image.tag }}"
          imagePullPolicy: {{ .Values.stablestudio.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.stablestudio.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 50
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 50
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.stablestudio.resources | nindent 12 }}
          {{- if .Values.stablestudio.env }}
          env:
          {{- range $k, $v := .Values.stablestudio.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
          {{- end }}
          {{- with .Values.stablestudio.args -}}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.stablestudio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stablestudio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.stablestudio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
{{- end }}
