apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-ss
  labels:
    {{- include "stablestudio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.stablestudio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stablestudio.selectorLabels" . | nindent 4 }}