apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-stable-diffusion.fullname" . }}
  labels: {{ - include "app-stable-diffusion.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ - include "app-stable-diffusion.selectorLabels" . | nindent 4 }}
