nameOverride: ""
fullnameOverride: ""

# Model
model:
  modelHFName: "stabilityai/stable-diffusion-2"
  modelRevision: ""
  # space separated files
  modelFiles: "768-v-ema.ckpt"

ui:
  # Set to false if you don't want to deploy the UI
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/neuro-inc/stablestudio
    pullPolicy: IfNotPresent
    tag: development
    imagePullSecrets: []
  service:
    port: 8080
  resources: {}
  nodeSelector: {}
  affinity: {}
  podAnnotations: {}

# Deployment
deployment:
  enabled: true
  replicaCount: 1

  args: []
  env:
    HUGGING_FACE_HUB_TOKEN: ""
    COMMANDLINE_ARGS: "--skip-version-check --skip-torch-cuda-test --allow-code --enable-insecure-extension-access --api --opt-channelslast --no-half --lowvram"
    HUGGINGFACE_HUB_CACHE: "/home/worker/app/huggingface-cache"

  image:
    repository: ghcr.io/neuro-inc/stable-diffusion-webui
    pullPolicy: IfNotPresent
    tag: development
    imagePullSecrets: []

  resources: {}

  healthChecks:
    endpoint: /health
    enabled: false
    delay: 300

  podAnnotations: {}

  nodeSelector: {}

  tolerations: {}
  # - key: platform.neuromation.io/job
  #   operator: Exists
  #   effect: NoSchedule
  # - key: nvidia.com/gpu
  #   operator: Exists
  #   effect: NoSchedule

  affinity: {}

priorityClassName: ""

# Service
service:
  port: 7860

# UIService
uiservice:
  port: 3000

# Ingress
ingress:
  enabled: false
  clusterName: ""

preset_name: ""


# Model download hook
modelDownload:
  initEnabled: true
  image:
    repository: huggingface/downloader
    tag: 0.17.3
    pullPolicy: IfNotPresent
  resources: {}

HFCacheVolume:
  enabled: true
  storage: 20Gi
  accessMode: ReadWriteOnce