nameOverride: ""
fullnameOverride: ""

# Model
model:
  # HF model name for example 768-v-ema.ckpt
  modelHFName: ""
  modelRevision: ""
  # space separated files for example 768-v-ema.ckpt
  modelFiles: ""


# StableStudio
stablestudio:
  # Deployment
  deployment:
    enabled: true
    replicaCount: 1

    args: [ ]

    image:
      repository: ghcr.io/neuro-inc/stablestudio
      pullPolicy: IfNotPresent
      tag: development
      imagePullSecrets: [ ]

    resources: { }

    healthChecks:
      endpoint: /health
      enabled: false
      delay: 300

    podAnnotations: { }

    nodeSelector: { }

    tolerations: { }
    # - key: platform.neuromation.io/job
    #   operator: Exists
    #   effect: NoSchedule
    # - key: nvidia.com/gpu
    #   operator: Exists
    #   effect: NoSchedule

    affinity: { }
  # Service
  service:
    port: 3000


# Deployment
deployment:
  enabled: true
  replicaCount: 1

  args: []
  env:
    HUGGING_FACE_HUB_TOKEN: ""
    COMMANDLINE_ARGS: ""
    HUGGINGFACE_HUB_CACHE: "/home/worker/app/huggingface-cache"

  image:
    repository: ghcr.io/neuro-inc/stable-diffusion-webui
    pullPolicy: IfNotPresent
    tag: development
    imagePullSecrets: []

  resources: {}

  healthChecks:
    endpoint: /health
    enabled: false
    delay: 300

  podAnnotations: {}

  nodeSelector: {}

  tolerations: {}
  # - key: platform.neuromation.io/job
  #   operator: Exists
  #   effect: NoSchedule
  # - key: nvidia.com/gpu
  #   operator: Exists
  #   effect: NoSchedule

  affinity: {}

priorityClassName: ""

# Service
service:
  port: 7860

# UIService
uiservice:
  port: 3000

# Ingress
ingress:
  enabled: false
  clusterName: ""
  className: ""
  annotations: { }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: HTTP
  # nginx.ingress.kubernetes.io/proxy-body-size: 15m
  # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: sd-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

preset_name: ""


# Model download hook
modelDownload:
  initEnabled: true
  image:
    repository: huggingface/downloader
    tag: 0.17.3
    pullPolicy: IfNotPresent
  resources: {}

HFCacheVolume:
  enabled: true
  storage: 20Gi
  accessMode: ReadWriteOnce