nameOverride: ""
fullnameOverride: ""

# Model
model:
  # HF model name for example 768-v-ema.ckpt
  modelHFName: ""
  modelRevision: ""
  # space separated files for example 768-v-ema.ckpt
  modelFiles: ""


# Deployment
deployment:
  enabled: true
  replicaCount: 1

  args: []
  env:
    HUGGING_FACE_HUB_TOKEN: ""
    COMMANDLINE_ARGS: ""
    HUGGINGFACE_HUB_CACHE: "/home/worker/app/huggingface-cache"

  image:
    repository: ghcr.io/neuro-inc/stable-diffusion-webui
    pullPolicy: IfNotPresent
    tag: development
    imagePullSecrets: []

  resources: {}

  healthChecks:
    endpoint: /health
    enabled: false
    delay: 300

  podAnnotations: {}

  nodeSelector: {}

  tolerations: {}
  # - key: platform.neuromation.io/job
  #   operator: Exists
  #   effect: NoSchedule
  # - key: nvidia.com/gpu
  #   operator: Exists
  #   effect: NoSchedule

  affinity: {}

priorityClassName: ""

# Service
service:
  port: 7860

# UIService
uiservice:
  port: 3000

# Ingress
ingress:
  enabled: false
  clusterName: ""

preset_name: ""


# Model download hook
modelDownload:
  initEnabled: true
  image:
    repository: huggingface/downloader
    tag: 0.17.3
    pullPolicy: IfNotPresent
  resources: {}

HFCacheVolume:
  enabled: true
  storage: 20Gi
  accessMode: ReadWriteOnce